services:
  backend:
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - storage-calculator

  db:
    container_name: db
    image: postgres:18.1-bookworm
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "${DB_PORT}:5437"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - storage-calculator

volumes:
  postgres-data:

networks:
  storage-calculator:
    driver: bridge
